- name: create user
  hosts: all
  become: yes
  roles:
    - create_user
    
- name: install httpd
  become_user: app-salaire
  hosts: [web]
  roles:
    - httpd
    
- name: install mariadb
  become_user: app-salaire
  hosts: [db]
  roles:
    - mariadb
