- name: create user
  hosts: [all]
  become: yes
  roles:
    - create_user
    
- name: install httpd
  hosts: [web]
  become_user: app-salaire
  roles:
    - httpd
    
- name: install mariadb
  hosts: [db]
  become_user: app-salaire
  roles:
    - mariadb
